server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///myself?serverTimezone=UTC
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    username: 1162375129@qq.com
    password: ruwquaakufcfjgad
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  redis:
      host: 127.0.0.1
      port: 6379
mybatis:
  mapper-locations: classpath:mapper/*/*.xml  #加载映射路径
  type-aliases-package: com.manage.modular.*.pojo
logging:
  level:
     com.manage.modular.*.mapper : debug